{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saas-framework.fullname" . }}-secrets
  labels:
    {{- include "saas-framework.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.app.database.url }}
  database-url: {{ .Values.app.database.url | quote }}
  {{- end }}
  {{- if .Values.app.redis.url }}
  redis-url: {{ .Values.app.redis.url | quote }}
  {{- end }}
  {{- if .Values.app.jwt.secretKey }}
  jwt-secret-key: {{ .Values.app.jwt.secretKey | quote }}
  {{- end }}
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
