apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas-framework

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: saas-framework
  app.kubernetes.io/part-of: microservices-platform
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "Python Framework for microservices"
  docs: "https://github.com/vhvplatform/python-framework"
