apiVersion: v1
kind: Service
metadata:
  name: saas-framework
  namespace: saas-framework
  labels:
    app.kubernetes.io/name: saas-framework
    app.kubernetes.io/component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saas-framework
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
